### ISSUE TITLE
function name "reset"  have the same name that function name "reset" from React Hook Form

### ISSUE THREAD

**Issue by kantar0** [tomliangg/react-hook-recaptcha#5]
I have something like that:
`const {
    register,
    handleSubmit, reset,
    formState: { errors },
    control,
  } = useForm()`
  
and I also need to use the reset

`const { reset } = useRecaptcha({
      containerId,
      successCallback,
      expiredCallback,
      sitekey,
      size: 'normal',
    });`
    
  and obviously throws me the error of type " Cannot redeclare block-scoped variable 'reset'."

**Comment by tomliangg** [comment]
The problem is "redeclare block-scoped variable". Basically JS doesn't let you declare the same variable name repeatedly in the same scope.
<img width="456" alt="image" src="https://user-images.githubusercontent.com/23287044/207731492-a30a1d6d-c21c-4e55-b548-3d7bc6e53d3d.png">

You can rename the field when you destruct an object:
<img width="236" alt="image" src="https://user-images.githubusercontent.com/23287044/207731704-00001540-02d1-4dc8-b882-5c6b6c54360a.png">


You can easily get around your issue by renaming one of the `reset` to something else:
```js
const { register, handleSubmit, reset, formState: { errors }, control, } = useForm();
const { reset: resetCaptcha } = useRecaptcha({ containerId, successCallback, expiredCallback, sitekey, size: 'normal', });
```
